### ISSUE TITLE
Using the wrong tooltip property for the "Finish" button.

### ISSUE THREAD

**Issue by Jan1503** [CodeGator/CG.Blazor#2]
https://github.com/CodeGator/CG.Blazor/blob/ecf4f3c291fd8a0eb89ae6f96a65dcc7322cf9ff/src/CG.Blazor/Components/Wizard/Wizard.razor#L119-L121

Hi!
Just tested your wizard component and found a little bug.
You've used the "NextButtonTooltip" for the Finish button instead of "FinishButtonTooltip".

Have a nice day!

**Comment by martycook** [comment]
Great catch! Thanks for letting know. Fixed in the next build.
